### PR TITLE
Cleanup and update names

### PR DESCRIPTION
**Pull request by ethanuppal**
This PR makes the following changes:

- Renames `tru` -> `true` and `fals` -> `false`.
- Replaces the older `mod.rs` structure with the [newer idiomatic structure](https://doc.rust-lang.org/rust-by-example/mod/split.html).
- Removes some redundant code.

Some questions: does `#[inline]` actually achieve anything (on the constructors for truth-y values)? Won't the compiler be smart enough to choose to inline (or not) when it deems necessary?

### CODE REVIEW

**Review by ekiwi — CHANGES_REQUESTED** [review]
I like how you renamed the files (I did not know that you could do that this way). The small fixes are also great.

However, please remove the renaming of `fals` and `tru`. I do not want to change that.

**Comment by ethanuppal** [comment]
I'm curious why you prefer `tru` over `true` and `fals` over `false`?

**Comment by ekiwi** [comment]
> I'm curious why you prefer tru over true and fals over false?

I don't see a reason to change it.

**Comment by ethanuppal** [comment]
> > I'm curious why you prefer tru over true and fals over false?
> 
> I don't see a reason to change it.

It follows established style guidelines, with examples including:

- Source: [The Rust Style Guide](https://doc.rust-lang.org/beta/style-guide/advice.html)
    > When a name is forbidden because it is a reserved word (such as `crate`)...Don't misspell the word (`krate`).

- Source: [Google style guidelines for C++](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules)
    > Do not abbreviate by deleting letters within a word.

- Source: [Microsoft style guidelines for VSCode](https://github.com/microsoft/vscode/wiki/Coding-Guidelines)
    > Use whole words in names when possible.

**Comment by ekiwi** [comment]
It does not matter. I currently do not want to do the work involved in changing all uses of this API without added functionality.

**Comment by ethanuppal** [comment]
I deprecated the old names, so it should still work.

**Comment by ethanuppal** [comment]
@ekiwi

**Comment by ekiwi** [comment]
> 
> I like how you renamed the files (I did not know that you could do that this way). The small fixes are also great.
> 
> However, please remove the renaming of fals and tru. I do not want to change that.

**Pull request merged**
